package learnspring.advanced;

import learnspring.advanced.LogTraceAspect;
import learnspring.advanced.trace.logtrace.LogTrace;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class AopConfig {
    @Bean
    public LogTraceAspect logTraceAspect(LogTrace logTrace){
        return new LogTraceAspect(logTrace);

    }
}
//2023-05-23 22:26:05.650  INFO 9349 --- [    Test worker] o.s.t.c.transaction.TransactionContext   : Began transaction (1) for test context [DefaultTestContext@10b3df93 testClass = learnJPAServiceTest, testInstance = learnspring.advanced.learnJPA.learnJPAServiceTest@452a32f2, testMethod = associatedTest@learnJPAServiceTest, testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@ea27e34 testClass = learnJPAServiceTest, locations = '{}', classes = '{class learnspring.advanced.LearnspringApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@68b6f0d6, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@2bd2b28e, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@674658f7, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@26425897, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@42e3ede4, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@4c2bb6e0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true, 'org.springframework.test.context.event.ApplicationEventsTestExecutionListener.recordApplicationEvents' -> false]]; transaction manager [org.springframework.orm.jpa.JpaTransactionManager@fbdba1c]; rollback [false]
//        2023-05-23 22:26:05.744  INFO 9349 --- [    Test worker] l.a.trace.logtrace.ThreadLocalLogTrace   : [da9448c3] CrudRepository.save(..)
//        Hibernate: insert into students (name) values (?)
//        Hibernate: insert into enrollments (student_id, teacher_id) values (?, ?)
//        Hibernate: insert into enrollments (student_id, teacher_id) values (?, ?)
//        2023-05-23 22:26:05.783  INFO 9349 --- [    Test worker] l.a.trace.logtrace.ThreadLocalLogTrace   : [da9448c3] CrudRepository.save(..) time=39ms
//        Hibernate: update enrollments set student_id=? where id=?
//        Hibernate: update enrollments set student_id=? where id=?
//        2023-05-23 22:26:05.805  INFO 9349 --- [    Test worker] o.s.t.c.transaction.TransactionContext   : Committed transaction for test: [DefaultTestContext@10b3df93 testClass = learnJPAServiceTest, testInstance = learnspring.advanced.learnJPA.learnJPAServiceTest@452a32f2, testMethod = associatedTest@learnJPAServiceTest, testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@ea27e34 testClass = learnJPAServiceTest, locations = '{}', classes = '{class learnspring.advanced.LearnspringApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@68b6f0d6, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@2bd2b28e, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@674658f7, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@26425897, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@42e3ede4, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@4c2bb6e0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true, 'org.springframework.test.context.event.ApplicationEventsTestExecutionListener.recordApplicationEvents' -> false]]
